# Generated by Django 4.2.7 on 2026-02-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='usage_limit',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='used_count',
        ),
    ]
