# Generated by Django 4.2.7 on 2026-02-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_promocode_usage_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-created_at']},
        ),
    ]
