# Generated by Django 4.2.7 on 2026-02-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_out_of_stock',
        ),
    ]
