# Generated by Django 4.2.7 on 2026-02-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_is_out_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
