# Generated by Django 4.2.7 on 2026-02-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_is_out_of_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
    ]
