# Generated by Django 4.2.7 on 2026-02-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
    ]
